[project]
name = 'waveform-community'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.waveform-community]
path = 'contracts/waveform-community.clar'
clarity_version = 2
epoch = 2.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
